name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Elm environment
        uses: JorelAli/setup-elm@v1
        with:
          # Version of Elm to use. E.g. 0.19.1
          elm-version: 0.19.1
      - name: install npm dependencies
        run: npm install
      - name: Test
        run: ./node_modules/elm-test/bin/elm-test
      - name: elm-review
        run: node_modules/elm-review/bin/elm-review  --template jfmengels/elm-review-unused/example
      # - name: check documentation
      #   run: |
      #     elm make --docs=docs.json
      #     rm docs.json
